# Generated by Django 5.2.7 on 2025-11-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Librarian',
        ),
    ]
